version: "2"

services:
  postgres:
    image: postgres:9.6-alpine
    container_name: contacts_postgres
    volumes:
      - ./docker_volumes/postgresql/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo
      POSTGRES_DB: demo
